const ActionTypes = {
  REQUEST_BROKER: 'REQUEST_BROKER',
  CHANGE_BROKER_STATUS: 'CHANGE_BROKER_STATUS',
  ADD_SENSOR_VALUE: 'ADD_SENSOR_VALUE',
  ADD_MESSAGE: 'ADD_MESSAGE',
  DISMISS_MESSAGE: 'DISMISS_MESSAGE'
};

export default ActionTypes
